# Docker Compose configuration for Visio Agent

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: visio
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U visio"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  visio-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CONFIG_KEY=${CONFIG_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ${DATA_PATH:-./data}:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  vector_extension:
    image: ankane/pgvector
    environment:
      POSTGRES_URL: postgres://postgres:${DB_PASSWORD}@postgres:5432/postgres
    depends_on:
      - postgres

  collaboration:
    image: visio-collab-service:latest
    environment:
      WEBSOCKET_PORT: 8793
      MAX_CONNECTIONS: 500
    depends_on:
      redis:
        condition: service_healthy

  jina:
    image: jinaai/jina:latest
    ports:
      - "54321:54321"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54321/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data: 