services:
  supabase:
    image: supabase/postgres
    ports:
      - "5432:5432"
      - "3000:3000" # Studio
      - "8000:8000" # Auth
    environment:
      POSTGRES_PASSWORD: secret
      STUDIO_PASSWORD: secret
      ENABLE_VECTOR: 'true'
      ENABLE_RLS: 'true'
      JWT_SECRET: ${JWT_SECRET}
      SITE_URL: ${VISIO_HOST}
    volumes:
      - supabase_data:/var/lib/postgresql/data
      - ./supabase/migrations:/supabase/migrations

volumes:
  supabase_data:

  vector_extension:
    image: ankane/pgvector
    depends_on:
      - supabase
    environment:
      POSTGRES_URL: postgres://postgres:secret@supabase:5432/postgres 

  visio-agent:
    environment:
      - CONFIG_KEY=${CONFIG_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ${DATA_PATH:-./data}:/app/data 

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: visio
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U visio"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  collaboration:
    image: visio-collab-service:latest
    environment:
      WEBSOCKET_PORT: 8793
      MAX_CONNECTIONS: 500
    depends_on:
      redis:
        condition: service_healthy 

  jina:
    image: jinaai/jina:latest
    ports:
      - "54321:54321"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54321/ready"]
      interval: 30s
      timeout: 10s
      retries: 3 